### PR TITLE
Feature/update to vrtk 3.3.0

### PR DESCRIPTION
**Pull request by dominik-rausch**
I skipped commit 2a212384b19e48d87ea92f1dfee80ec8de7c894a, which causes VRTK_SDKManager.instance to return null during OnEnable

### CODE REVIEW

**Review by LukasReindlGit — APPROVED** [review]

**Review by burnedikt — CHANGES_REQUESTED** [review]
Due to the removal of commit https://github.com/Innoactive/IA-unity-VR-toolkit-VRTK/commit/2a212384b19e48d87ea92f1dfee80ec8de7c894a all commit hashes have changed which in turn means, further updates from VRTK in the future will be hard / impossible (because git will think the original commits that have now been rebased in our repo are not yet part of our repo and will try to reapply them which will essentially turn into one big merge conflict mess). So my proposal would be: Do a normal merge and revert the changes to the SDKManager in an additional commit.

**Comment by dominik-rausch** [comment]
done!

**Review by burnedikt — APPROVED** [review]

**Comment by burnedikt** [comment]
apppproooooooooooved

**Comment by dominik-rausch** [comment]
rebased, needs reapproval

**Comment by burnedikt** [comment]
nah, it's still approved (or you didn't push)? ;)

**Comment by dominik-rausch** [comment]
oops, wrong PR, meant the Hub-SDK PR 😇

**Pull request merged**
