### PR TITLE
Update from VRTK Base repo (3.3.0)

### PR DESCRIPTION
**Pull request by burnedikt**
Updates the master of our Fork with the latest changes from the original VRTK

### CODE REVIEW

**Comment by tomwim** [comment]
Do not see why this should cause any troubles 👍 - but checking first

**Review by tomwim — APPROVED** [review]

**Comment by tomwim** [comment]
@burnedikt the two fixes are already in feature/update-to-3.3.0-alpha but apparently the merge does not like them...

**Comment by burnedikt** [comment]
so you're telling me 747a152 and 2b022e0 are already part of `feature/update-to-3.3.0-alpha` but they don't show up here on github?

**Comment by tomwim** [comment]
They were for whatever reason not in feature/update-to-3.3.0-alpha...
Stonefox just accepted my PR in VRTK. So I just merge and update everything and create a final PR into master with all changes.

**Comment by tomwim** [comment]
Tried to merge latest VRTK again and error persists...probably caused by different commit hashes.
I suggest just using the two extra commits I made. They resolve all issues.

**Comment by burnedikt** [comment]
Well, after some git blaming: The problem exists because our commits introduced some bugs which were fixed in the original VRTK but when merging, we took our version and thus we had to manually fix it again: 

- 2b022e0ed80d5d6afc92aaadba09ab8065c1726a fixes bug we introduced in 609206e383e6f04057420d721201a2861ba6731e (the correct procedure would thus be to squash 2b022e0ed80d5d6afc92aaadba09ab8065c1726a into 609206e383e6f04057420d721201a2861ba6731e )
- also, 
747a152 fixes the duplicate `TouchpadTwo` which only exists because we've manually added it in 1cec95dce5f832af457e6b312e2d58f9fad48b4e and then got it in twice because of the merge with the original VRTK (which also contains `TouchpadTwo`. Again, squashing 747a152 with 1cec95dce5f832af457e6b312e2d58f9fad48b4e should do the trick.

**Comment by tomwim** [comment]
@burnedikt Included latest fix from VRTK/master and rebased + squashed again. Looking good now

**Pull request merged**
