### PR TITLE
Change folder structure

### PR DESCRIPTION
**Pull request by tomwim**
Move everything in VRTK/Assets/VRTK/* to VRTK/* to reduce the length of the path

### CODE REVIEW

**Comment by SimonTheSourcerer** [comment]
i  would remove examples/legacyexamples

**Review by SimonTheSourcerer — APPROVED** [review]

**Comment by burnedikt** [comment]
just a reality check: you are aware that changing the folder structure will make potential updates from the usptream project way harder? This is okay if we do not expect any updates from VRTK anymore but otherwise, meh.

**Comment by burnedikt** [comment]
might want to consider `git subtree` which allows "submoduling" a git repository but excluding certain files and folders (and maybe also changing folder structure)? or as discussed: just inline the entire code within the VRTK-Extension (duplicates code but at least doesn't fuck up other project potentially using this repository (like the Hub-SDK))

**Comment by tomwim** [comment]
> just a reality check: you are aware that changing the folder structure will make potential updates from the usptream project way harder? This is okay if we do not expect any updates from VRTK anymore but otherwise, meh.

Yes, but there won't be any updates on 3.3.0
I have the feeling at some point an update from Steam VR or something will break compatibility with VRTK 3.3.0 and then we are forced to change anyways. So I think we do not have to worry about updates

I will look into subtrees though

**Comment by burnedikt** [comment]
> > just a reality check: you are aware that changing the folder structure will make potential updates from the usptream project way harder? This is okay if we do not expect any updates from VRTK anymore but otherwise, meh.
> 
> Yes, but there won't be any updates on 3.3.0
> I have the feeling at some point an update from Steam VR or something will break compatibility with VRTK 3.3.0 and then we are forced to change anyways. So I think we do not have to worry about updates
> 
> I will look into subtrees though

last state of discussion with @SimonTheSourcerer was that we will "insource" the entire VRTK code into the VRTK Extensions repo afaik. If subtrees can do the job that would probably be nicer but either way this fork here will ideally not be altered.

**Pull request closed without merging**
