### PR TITLE
Feature/update to latest vrtk

### PR DESCRIPTION
**Pull request by tomwim**

### CODE REVIEW

**Comment by burnedikt** [comment]
@tomwim this party has conflicts. Also, the last 11 commits should probably not be part of this PR as they are already part of the branch we want to merge in?

**Comment by tomwim** [comment]
@burnedikt I know, I know ;) Not done yet. I just rebased to VRTK/master to see conflicts
I am actually not a 100% sure if thats the right way. My idea was to first rebase to VRTK/master and then rebase again to feature/update-to-3.3.0-alpha?

**Comment by burnedikt** [comment]
I would not do a rebase in this case, but just a normal merge of this branch with the vrtk-master. Because otherwise, we'll need to overwrite the entire history of our fork's master after the rebase which will potentially break all existing project that use older SDK versions which reference certain commits on the VRTK fork which will be gone after the rebase (since the hash of every commit will change). So really go for the merge here instead.

**Comment by tomwim** [comment]
Closed an opened a new PR https://github.com/Innoactive/IA-unity-VR-toolkit-VRTK/pull/39
@burnedikt that should be good now

**Pull request closed without merging**
