### PR TITLE
Update SharedMethods with latest version from VRTK

### PR DESCRIPTION
**Pull request by tomwim**
- Needed because of WSA/UWP issues

### CODE REVIEW

**Comment by burnedikt** [comment]
are these changes from us or from VRTK? if they are coming from VRTK then we should simply do a merge of VRTK:master to `feature/update-to-3.3.0-alpha`

**Comment by tomwim** [comment]
It's changes from VRTK that I simply copied, I'll compare VRTK:master with feature/update-to-3.3.0-alpha and willl create a new PR if it makes sense to take all of VRTK:master

**Comment by burnedikt** [comment]
if you do that, you will get a 100% conflict on the file. Instead, pull in the changes from the other repository so git notices the commits and can do a clean merge. By just copying over files, git will think: "Oh, VRTK modified this file and the lines and Innoactive did as well, so now, the entire file and every single change in there will be a conflict - have fun!"

**Comment by tomwim** [comment]
Aaaah, I see. Will do!

**Comment by burnedikt** [comment]
so this can be closed @tomwim ?

**Comment by tomwim** [comment]
Now in https://github.com/Innoactive/IA-unity-VR-toolkit-VRTK/pull/39

**Pull request closed without merging**
